- hosts: all
  become: yes

  roles:
    - robertdebock.revealmd

  tasks:
    - name: create directory
      file:
        path: /data
        state: directory

    - name: place content
      synchronize:
        src: files/
        dest: /data

    - name: show presentation url
      debug:
        msg: the presenation is available on http://localhost:8000/
